accounts/urls.py
from django.conf.urls   import include, url
from django.contrib     import admin
from accounts           import views

urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
]

bookmarks/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from bookmarks import views
from bookmarks.models import Article

urlpatterns = [

    url(r'^silo/$',			                        login_required(views.ArticleListView.as_view()),        name='silo'),
    url(r'^new-article/$',	                        login_required(views.ArticleCreateView.as_view()),      name='new-article'),
    url(r'^edit-article/(?P<pk>[0-9]+)/$',          login_required(views.ArticleUpdateView.as_view()),      name='edit-article'),
    url(r'^archive-article/(?P<article_id>\d+)/$',  views.archive_article,                                  name='archive-article'),
    url(r'^unarchive-article/(?P<article_id>\d+)/$',views.unarchive_article,                                name='unarchive-article'),
    url(r'^archives/$',	                            login_required(views.ArchivesListView.as_view()),       name='archives-list'),
    url(r'^manage-tags/$',                          views.manage_tags,                                      name='manage-tags'),
    url(r'^article_viewed/$',                       views.ajax_article_recently_viewed,                     name='recently-viewed-update'),
    url(r'^topics/$',                               views.topic_list,                                       name='topic-list'),

]

bookwormbud/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', 	include('accounts.urls', 	namespace='accounts')),
    url(r'^',           include('bookmarks.urls',	namespace='bookmarks')),
]
# ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookmarks/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

from taggit.managers import TaggableManager
from taggit.models import TagBase, GenericTaggedItemBase
from taggit.utils import require_instance_manager

#----------------------------------------------------------------------------------------------------

class ArticleQueryset(models.query.QuerySet):
    def archived(self):
        return self.filter(archived=True)
    def current(self):
        return self.filter(archived=False)
    def category(self, this_category):
        return self.filter(category=this_category)
    def all_categories(self):
        categories = self.values('category').distinct()
        filtered_categories = [this_dict['category'] for this_dict in categories if this_dict['category']]
        return filtered_categories

#----------------------------------------------------------------------------------------------------

class ArticleManager(models.Manager):
    def get_queryset(self):
        return ArticleQueryset(self.model, using=self._db)
    def archived(self):
        return self.get_queryset().archived()
    def current(self):
        return self.get_queryset().current()
    def category(self):
        return self.get_queryset().category()
    def all_categories(self):
        return self.get_queryset().all_categories()

#----------------------------------------------------------------------------------------------------


class MyTag(TagBase):
    user = models.ForeignKey(User)

    def __unicode__(self):
        return self.slug

    def save(self, *args, **kwargs):
        slugged_name    = self.slugify(self.name)
        self.name       = slugged_name
        super(MyTag, self).save( *args, **kwargs)

#----------------------------------------------------------------------------------------------------

class MyTaggedManager(GenericTaggedItemBase):
    tag = models.ForeignKey(MyTag, related_name="%(app_label)s_%(class)s_items")

#----------------------------------------------------------------------------------------------------
#template for the table
class Article(models.Model):
    url             = models.CharField(max_length=256, unique=True)
    title           = models.CharField(max_length=256, default="None", blank=True)
    created         = models.DateTimeField(auto_now_add=True)
    last_read       = models.DateTimeField(null=True, blank=True)
    viewed_count    = models.IntegerField(default=0)
    archived        = models.BooleanField(default=False, blank=True)
    user            = models.ForeignKey(User, null=True, blank=True)

    #rules that govern working of table
    def __unicode__(self):
        return self.title

    def archive(self):
        self.archived = True
        self.save()

    def unarchive(self):
        self.archived = False
        self.save()

    objects = ArticleManager()

    tags = TaggableManager(through=MyTaggedManager)

    def get_absolute_url(self):
        return reverse('bookmarks:silo')

#----------------------------------------------------------------------------------------------------

class Topic(models.Model):
    title       = models.CharField(max_length=256)
    description = models.TextField(null=True, blank=True)

#----------------------------------------------------------------------------------------------------

class ArticleTopic(models.Model):
    class Meta:
        unique_together = (('topic', 'article',))

    topic   = models.ForeignKey('bookmarks.Topic')
    article = models.ForeignKey('bookmarks.Article')

bookmarks/forms.py
import requests, re
from lxml import html

from django                         import forms
from django.forms.widgets           import Select
from django.core.exceptions         import ValidationError
from django.contrib.auth.models     import User
from django                         import forms
from django.template.defaultfilters import slugify
from django.contrib.admin.widgets   import AdminDateWidget
from django.forms.extras.widgets    import SelectDateWidget
from django.forms.fields            import DateField

from bookmarks.models       import Article, MyTag
from bookmarks.functions    import ensure_http

def process_title(url):
    def _search_for_title(url):
        url = ensure_http(url)
        try:
            r = requests.get(url)
            content = r.text
            t = html.document_fromstring(content)
            return t.find(".//title").text
        except:
            return None

    title = _search_for_title(url)
    print(title)
    return title or "Couldn't find a title"

#----------------------------------------------------------------------------------------------------

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ('url', 'title', 'user')

    url     = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'required'}),
                  max_length=256, label='URL', required=True)
    title   = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "I'll grab the page's title"}),
                  max_length=256, label='Title', required=False)
    user    = forms.CharField(widget=forms.HiddenInput())

    def clean(self):
        title = self.cleaned_data['title']
        url   = self.cleaned_data['url']
        title = process_title(url)
        self.cleaned_data['title'] = title
        self.instance.title = title
        username = self.cleaned_data['user']
        user = User.objects.get(username=username)
        self.cleaned_data['user'] = user
        super(ArticleForm, self).clean()
        return self.cleaned_data

#----------------------------------------------------------------------------------------------------

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ('url', 'title', 'user')

    url     = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'required'}),
                  max_length=256, label='URL', required=True)
    title   = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "I'll grab the page's title"}),
                  max_length=256, label='Title', required=False)
    user    = forms.CharField(widget=forms.HiddenInput())

    def clean(self):
        try:
            title = self.cleaned_data['title']
            url   = self.cleaned_data['url']
            title = process_title(url)
            self.cleaned_data['title'] = title
        except:
            pass
        username = self.cleaned_data['user']
        user = User.objects.get(username=username)
        self.cleaned_data['user'] = user
        super(ArticleForm, self).clean()
        return self.cleaned_data

#----------------------------------------------------------------------------------------------------

class EditArticleForm(forms.ModelForm):
    url     = forms.CharField(required=False)
    title   = forms.CharField(required=False)
    class Meta:
        model = Article
        fields = ('url', 'title')

#----------------------------------------------------------------------------------------------------

class TagForm(forms.ModelForm):
    name = forms.CharField(label="", required=False)
    class Meta:
        model = MyTag
        fields = ('name',)

    def clean_name(self):
        name = self.cleaned_data['name']
        if not name:
            raise ValidationError("Name is empty")
        return slugify(name)


def get_tag_choices():
    #reading tags to get all values
    tags = MyTag.objects.all()#collect tags
    CATEGORY_CHOICES = [('', '')]#default selection
    if tags:
        for tag in tags:
            CATEGORY_CHOICES.append((tag.name, tag.name))
    return CATEGORY_CHOICES

#----------------------------------------------------------------------------------------------------
#this class uses preformatted fields, like model,
#just setting up structure of a multiple choice field
class TagSelectForm(forms.ModelForm):
    class Meta:
        model = MyTag
        fields = ('name',)

    name = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        choices=get_tag_choices()
    )



class AddedDateCalendarForm(forms.Form):
    added_start_date  = forms.DateField()
    added_end_date    = forms.DateField()


class LastViewedDateCalendarForm(forms.Form):
    last_viewed_start_date  = forms.DateField()
    last_viewed_end_date    = forms.DateField()
    # field1 = forms.DateField(widget=SelectDateWidget(empty_label="Nothing"))

    # field2 = forms.DateField(
    #     widget=SelectDateWidget(
    #         empty_label=("Choose Year", "Choose Month", "Choose Day"),
    #     ),
    # )

    # A custom empty label with tuple
    # field2 = forms.DateField()

bookmarks/templates/bookmarks/add_article.html
{% extends 'base.html' %}

{% load bootstrap extras %}

{% block body_block %}

<style>
	footer{
		background: transparent;
	}

	div{
		display: block;
	}
</style>
	<form action="" method="post">
		{% csrf_token %}
		<input id="id_user" name="user" type="hidden" />

		<section id="url-and-title" class="row">
			<div class="col-md-8">

				<h4>URL</h4>
				<span>
					<div class="col-md-8" style="width:100%">
				        <input class="form-control" id="id_url" maxlength="256" name="url" placeholder="required" type="text" />
					</div>
				</span>

			</div>

			<div class="help-text" style="width:100%">
				<p>Try to avoid ugly urls like http://www.art.com/artgallery/default.asp?sid=9DF4BC%200580DF11D3ACB60090271E26A8&command=freelist</p>
				<p>That one should be cleaned to http://www.art.com/artgallery/</p>
				<p>They're often randomly generated and won't work in a few days.</p>
			</div>





			<div class="col-md-8">

				<h4>Title</h4>

				<div class="col-md-8">
			            <input class="form-control" id="id_title" maxlength="256" name="title" placeholder="I&#39;ll grab the page&#39;s title" type="text" />
				</div>
				<div class="help-text">
					<p>If you leave the title blank, it will try to find it on the page. This is usually what you see in the top of the screen (the tab).<p>
					<p>If it's a really important article, it's usually best to make a title you'll remember.</p>
				</div>
			</div>
		</section>

		<section id="multiple" class="row">
			<div class="col-md-8">

				<h4>Add existing tags</h4>
				<span>
					<select  style="width:90%;" multiple="multiple" id="existing_tags" name="existing_tags">
						{% for tag in tags %}
							<option value="{{tag.name}}">{{tag.name}}</option>
						{% endfor %}
					</select>
				</span>

				<div class="help-text" style="width:100%">
					<p>Add tags you've already created.</p>
					<p>This and 'new tags' are separated so you can hit enter quickly when your search matches a tag.</p>
				</div>

				<h4>Add new tags</h4>
				<span>
					<select  style="width:90%;" multiple="multiple" id="new_tags" name="new_tags"></select>
				</span>

				<div class="help-text">
					<p>Hit enter or comma (,) to make a new tag. Spaces are allowed, but they will be turned into dashes (-) to make tags easier to process.<p>
				</div>
			</div>
		</section>
		<br/>
		{% for space in user.space_set.all %}
			<button type="button" class="btn">{{ space.name }}</button>
		{% endfor %}
		<br/><br/>
		<input type="hidden" name="user" value="{{ request.user }}" />
		<input type="submit" name="submit" value="Add new article"/>
	</form>

	<!-- /*<style>
		.select2-drop {
	    	display: none !important;
		}
	</style>*/ -->

	<script type="text/javascript">
	$(document).ready(function() {
	    $("#existing_tags").select2({});
		$("#new_tags").select2({
	        tags: true,
	        tokenSeparators: [',']
	    });
	});

	</script>
{% endblock %}

bookmarks/templates/bookmarks/archives_list.html
{% extends 'base.html' %}

{% load add_get_parameter %}
(% load extras %)
{% block body_block %}

<!-- http://jsfiddle.net/RetMp/963/ -->


<head>

    <style>
        #article-link .url-text {
            position: relative;
            visibility: hidden;
        }
    
        {% if not articles %}
            body{
                cursor:pointer;
            }
        {% endif %}
    </style>
</head>


{% if articles %}
    <div style="width:94%;">
        {% for article in articles %}
                  <div class="col-md-4 article-link">
                    <div class="panel panel-default hover">
                        <div class="panel-heading"><h4 class="url-link">{{ article.title }}</h4></div>
                        <div class="panel-body">
                            <p>&nbsp;<span class="url-text">{{ article.url }}</span></p>
                            <a href="{% url 'bookmarks:edit-article' article.id %}"><div class="article_button">Edit</div></a>
                            <a href="{% add_get unarchive=article.id %}"><div class="article_button"><p>Un-archive</p></div></a>
                            <a href="{% add_get delete=article.id %}"><div class="article_button">Delete</div></a>
                            <div style="margin-top:8px;">
                                {% for tag in article.tags.all %}
                                    <p class="tag">{{ tag.name }}</p>
                                {% endfor %}
                            </div>
                        </div>
                      </div>
                  </div>
        {% endfor %}
    </div>
    
    <script>
        $('.article-link a').click(function(e){
          e.stopPropagation();
        });
        
        $('.article-link').on('click',function(e){
            var url = $( this ).find( ".url-text" ).text();
            window.open(url, '_blank')
        });
    </script>

{% else %}
    <div>
        <h2 id="no-articles">You don't have any archived articles</h2>
    </div>
    
    <script>

        var url = {% url 'bookmarks:silo' %};

        $('body').on('click',function(e){
            window.location = url
        });
        ;
    </script>
{% endif %}
<br/><br/>






{% endblock %}

bookmarks/templates/bookmarks/edit_article.html
{% extends 'base.html' %} 
{% load bootstrap extras %} 
{% block body_block %} 
    <form id="article_form" method="post" action="" enctype="multipart/form-data">
        {% csrf_token %} {{ form|bootstrap }}

        <section id="multiple" class="row">
            <div class="col-md-8">
                <span>
                    
                    <h4>Add existing tags</h4>
    				</span>
    					<select  style="width:90%;" multiple="multiple" id="existing_tags" name="existing_tags">
                            {% for tag in tags %}
                                {% if tag in article.tags.all %}
                                    <option selected="selected" value="{{tag.slug}}">{{tag.name}}</option>
                                {% else %}
                                    <option value="{{tag.slug}}">{{tag.name}}</option>
                                {% endif %}
                            {% endfor %}
    					</select>                
    				</span>
    				<h4>Add new tags</h4>
    				</span>
    					<select  style="width:90%;" multiple="multiple" id="new_tags" name="new_tags"></select>                
    				</span>
                </span>
            </div>
        </section>
        

        <br/>
        <input type="submit" name="submit" value="Edit article" />
    </form>

    <script type="text/javascript">
    $(document).ready(function() {
	    $("#existing_tags").select2({}); 
		$("#new_tags").select2({
	        tags: true,
	        tokenSeparators: [',']
	    }); 
	});
	
    </script>
    
{% endblock %}

bookmarks/templates/bookmarks/manage_tags.html
{% extends 'base.html' %}

{% load bootstrap %}

{% block body_block %}
    
    {% for message in messages %}
        <div style="color:red;">{{ message }}</div>
    {% endfor %}
    
    <div class="help-text">
        <p>Hit enter or comma (,) to make a new tag. Spaces are allowed, but they will be turned into dashes (-) to make tags easier to process.<p>

    </div>

    
	<form id="tag_form" method="post" action="." enctype="multipart/form-data">
		{% csrf_token %}

        <section id="multiple" class="row">
            <div class="col-md-8">
                <h4>Add new tags<h4>
                <p>
                    <select  style="width:90%;" multiple="multiple" name="added_tags" id="added_tags">
                    </select>                
                 </p>
             </div>
        </section>
        {% if tags %}
        <section id="multiple" class="row">
            <div class="col-md-8">
                <h4>Delete tags</h4>
                <p>
                    <select  style="width:90%;" multiple="multiple" name="deleted_tags" id="deleted_tags">
                        {% for tag in tags %}        
                            <option value="{{tag.slug}}">{{tag.name}}</option>
                        {% endfor %}
                    </select>                
                 </p>
             </div>
        </section>
        {% endif %}
        
        <section id="multiple" class="row">
            <div class="col-md-8">
                <h4>Add new spaces<h4>
                <p>
                    <select  style="width:90%;" multiple="multiple" name="new_spaces" id="new_spaces">
                    </select>                
                 </p>
             </div>
        </section>
        {% if tags %}
        <section id="multiple" class="row">
            <div class="col-md-8">
                <h4>Delete spaces</h4>
                <p>
                    <select  style="width:90%;" multiple="multiple" name="spaces_to_delete" id="spaces_to_delete">
                        {% for space in spaces %}        
                            <option value="{{space.name}}">{{space.name}}</option>
                        {% endfor %}
                    </select>                
                 </p>
             </div>
        </section>
        {% endif %}
            
		<br/>
	       <input type="submit" name="submit" value="Submit changes"/>
    </form>


<script type="text/javascript">
    $(document).ready(function() {
        $("#deleted_tags").select2({
        }); 
    });

    $(document).ready(function() {
        $("#added_tags").select2({
            tags: true,
            tokenSeparators: [',']
        }); 
    });
    
    $(document).ready(function() {
        $("#new_spaces").select2({
        }); 
    });

    $(document).ready(function() {
        $("#spaces_to_delete").select2({
            tags: true,
            tokenSeparators: [',']
        }); 
    });
    
</script>
{% endblock %}

bookmarks/templates/bookmarks/silo.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap add_get_parameter %}
{% load title_filter %}
{% load widget_tweaks %}


<!-- http://jsfiddle.net/RetMp/963/ -->

{% block body_block %}
            <style>
                {% if not articles %}
                    body{
                        cursor:pointer;
                    }
                {% endif %}

                .date_field {
                    position: relative;
                    z-index: 999;
                }
            </style>

    {% for message in messages %}
        <div style="color:green;font-size:22px;text-align:center;"><p>{{ message }}</p></div>
    {% endfor %}

    {% if articles %}

            <div style="width:94%;">
                    <div class="help-text">
                        <p>You can filter your articles by tags. Articles with the most tags matched come first, and all articles that have at least one tag will show up.</p>
                    </div>

                    <div>
                        <h4>Tags</h4>
                        <!-- the novalidate part is required now: http://stackoverflow.com/questions/22148080/an-invalid-form-control-with-name-is-not-focusable -->
                        <form id="category_form" method="post" action="{% url 'bookmarks:silo' %}" name="category_form" novalidate "enctype="multipart/form-data">
                              {% csrf_token %}

                              <section id="multiple" class="row">
                                  <div class="col-md-8">
                                      <span>
                                          <select  style="width:90%;" multiple="multiple" id="selected_tags" name="selected_tags">
                                              {% for tag in tags %}
                                                  {% if tag.slug in tags_chosen %}
                                                      <option selected="selected" value="{{tag.slug}}">{{tag.name}}</option>
                                                  {% else %}
                                                      <option value="{{tag.slug}}">{{tag.name}}</option>
                                                  {% endif %}
                                              {% endfor %}
                                          </select>
                                      </span>
                                   </div>
                              </section>
                              <br/>

                              <!-- making the jquery datepicker show up above the edit, archive, and delete buttons
                              http://stackoverflow.com/questions/11533161/jquery-ui-datepicker-change-z-index -->


                        <div class="advanced-search-form" id="advanced-search-form">
                            <h4>Filter by the day the article was added to BookwormBuddy:</h4>
                            <p><b>Start date:</b> {{ added_date_form.added_start_date|add_class:"date_field" }} <b>End date:</b> {{ added_date_form.added_end_date|add_class:"date_field" }}</p>
                            <br>
                            <h4>Filter by the last day the article was viewed:</h4>
                            <p><b>Start date:</b> {{ last_viwed_date_form.last_viewed_start_date|add_class:"date_field" }} <b>End date:</b> {{ last_viwed_date_form.last_viewed_end_date|add_class:"date_field" }}</p>
                        </div>
                        <br>
                        <p><input type="submit" name="submit" value="Search"/> <input type="button" id="advanced-search-button" class="advanced-search-button" value="Advanced search"></p>
                        <br/>
                    </form>
                    <br/>
                    </div>


                <div class="help-text">
                    <p>Click within the box for each article to open it in a new window.</p>
                    <p>"Archive" sends an article to a silo of old articles. Careful, "Delete" removes it permanently.</p>
                    <p>Articles are ordered by total amount of views by default. You can change this with the "Order by" tabs.</p>
                    <!-- <p>Settings can be changed in the "Settings" tab in the upper right hand "Account" box.</p> -->


                </div>

            	{% for article in articles %}
                    <div  class="col-md-4 article-link" data-article={{article.id}}>

                        <div class="panel panel-default hover hover-box">

                            <div class="panel-heading hover-box"><h4 class="url-link article-title">{{ article.title|shorten_title }}</h4></div>
                            <input type="button" class="more-info-button" value="More info">
                            <div class="more-info">
                                {% if article.last_read %}
                                    <p>Last viewed: {{ article.last_read }}</p>
                                {% else %}
                                    <p>Last viewed: never</p>
                                {% endif %}
                                <p>Created date: {{ article.created }}</p>
                                <p>Views: {{ article.viewed_count }}</p>
                                <p>URL: {{ article.url }}</p>
                            </div>
                            <p>&nbsp;<span class="url-text popup-span">{{ article.url }}</span></p>
                            <div class="panel-body">
                                <a href="{% url 'bookmarks:edit-article' article.id %}"><div class="article_button">Edit</div></a>
                                <a href="{% add_get archive=article.id %}"><div class="article_button"><p>Archive</p></div></a>
                                <a href="{% add_get delete=article.id %}"><div class="article_button">Delete</div></a>
                                <div style="margin-top:8px;">
                                    {% for tag in article.tags.all %}
                                        <p class="tag">{{ tag.name }}</p>
                                    {% endfor %}
                                </div>
                            </div>
                          </div>
                    </div>
            	{% endfor %}
        </div>

    {% else %}
        <h2 style="text-align:center;">Go make some articles!</h2>
    {% endif %}



    <script>
        // limits article clicks to articles only, and not the upper right nav tab
        $('.article-link a').click(function(e){
          e.stopPropagation();
        });

        $('.article-link div .more-info-button').click(function(e){
          e.stopPropagation();
        });

        // allows to click on the entire box of an article and open new page
        $('.article-link').on('click',function(e){
            var url = $( this ).find( ".url-text" ).text();
            window.open(url, '_blank')

            var articleTitle = ($(this).find('div div .article-title').text());

            // sends ajax request updating info
            var articleId = $(this).attr('data-article');
            var recentlyViewedUrl = {% url 'bookmarks:recently-viewed-update' %};
            $.ajax({
                url: recentlyViewedUrl,
                type: 'POST',
                dataType: 'html',
                data: {
                    articleID: articleId,
                    ip: '104.131.73.226'
                },


            });

            return false;

        });

        // if there aren't any articles, turns the entire body into a link to add new articles
        {% if not articles %}
            var url = {% url 'bookmarks:new-article' %};
            $('body').on('click',function(e){
                window.location = url
            });
        {% endif %}



        function matchStart (term, text) {
            if (text.toUpperCase().indexOf(term.toUpperCase()) == 0) {
                return true;
            }

            return false;
        }

        // the select2 JS that makes it function
        $(document).ready(function() {
            // $.fn.select2.amd.require(['select2/compat/matcher'], function (oldMatcher) {
                $("#selected_tags").select2({
                    // matcher: oldMatcher(matchStart)
                });
            // });
        });

        // slide displays the "More info" button and changes it's name
        $(function(){
            $(".more-info-button").click(function(){
                if ( $(this).val() == "More info"){
                    $(this).val("Less info");
                } else {
                    $(this).val("More info");
                }

                $(this).parent().find('.more-info').slideToggle();
            });
        });

        // supposed to install the datepicker
        // http://hexonio.com/blog/2012/03/07/calendar-picker-django-forms/
        $(function() {
            $( "#id_added_start_date" ).datepicker();
            $( "#id_added_end_date" ).datepicker();
            $( "#id_last_viewed_start_date" ).datepicker();
            $( "#id_last_viewed_end_date" ).datepicker();
        });

        $(function(){
            $("#advanced-search-button").click(function(){

                $(".advanced-search-form").slideToggle();

                if ( $(this).val() == "Advanced search"){
                    $(this).val("Hide advanced search");
                } else {
                    $(this).val("Advanced search");
                }
            });
        });

    </script>

{% endblock %}