accounts/urls.py
from django.conf.urls   import include, url
from django.contrib     import admin
from accounts           import views

urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
]

bookmarks/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from bookmarks import views
from bookmarks.models import Article

urlpatterns = [

    url(r'^silo/$',			                        login_required(views.ArticleListView.as_view()),        name='silo'),
    url(r'^new-article/$',	                        login_required(views.ArticleCreateView.as_view()),      name='new-article'),
    url(r'^edit-article/(?P<pk>[0-9]+)/$',          login_required(views.ArticleUpdateView.as_view()),      name='edit-article'),
    url(r'^archive-article/(?P<article_id>\d+)/$',  views.archive_article,                                  name='archive-article'),
    url(r'^unarchive-article/(?P<article_id>\d+)/$',views.unarchive_article,                                name='unarchive-article'),
    url(r'^archives/$',	                            login_required(views.ArchivesListView.as_view()),       name='archives-list'),
    url(r'^manage-tags/$',                          views.manage_tags,                                      name='manage-tags'),
    url(r'^article_viewed/$',                       views.ajax_article_recently_viewed,                     name='recently-viewed-update'),
    url(r'^topics/$',                               views.topic_list,                                       name='topic-list'),

]

bookwormbud/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', 	include('accounts.urls', 	namespace='accounts')),
    url(r'^',           include('bookmarks.urls',	namespace='bookmarks')),
]
# ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>BookwormBuddy</title>

        {% load static %}

        <!-- Load javascript libraries -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
        <link type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.css" rel="Stylesheet" />

        <script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.1/js/bootstrap.min.js"></script>
        <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.4/css/bootstrap.css" rel="stylesheet">

        <script src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/js/select2.min.js"></script>
        <link href="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/css/select2.min.css" rel="stylesheet" />

        <link href="{% static "css/main.css" %}" rel="stylesheet" type="text/css" />

        <!-- semantic -->
        <!-- <link href="https://cdnjs.com/libraries/semantic-ui" rel="stylesheet"/> -->
        <!-- Fonts -->
        <!--<link href='//fonts.googleapi    'accounts',
    'bookmarks',    'accounts',
    'bookmarks',s.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css'>-->

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and static queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
                <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
                <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->


    </head>

    <body>
        <script>
            // check help text exists so we need button
            if ( $(".help-text").length < 1) {
                $("#help-button").hide();
            }
        </script>

        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'bookmarks:silo' %}">BookwormBuddy</a>
                </div>

                <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                <div id="navbar" class="navbar-collapse collapse">
                    <span style="position:fixed; left:700px; top:15px;">{{request.user.username}}</span>
                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}

                            <li class="dropdown">
                                Account
                                <span class="caret"></span>

                            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                <li class="dropdown-header"><a href="{% url 'bookmarks:silo' %}">Home</a></li>
                                <li class="dropdown-header"><a href="{% url 'bookmarks:new-article' %}">Make a new article</a></li>
                                <li class="dropdown-header"><a href="{% url 'bookmarks:archives-list' %}">List archived articles</a></li>
                                <li class="dropdown-header"><a href="{% url 'bookmarks:manage-tags' %}">Manage tags</a></li>
                                <li class="divider"></li>
                                <li class="dropdown-header"><a href="/helpdesk/">Helpdesk</a></li>
                                <li class="divider"></li>
                                <li class="dropdown-header"><a href="{% url 'accounts:logout' %}">Log out</a></li>
                            </ul></li>
                            {% else %}
                            <li class="dropdown"><a data-toggle="dropdown" class=" dropdown-toggle" href="#">
                                <li class="dropdown-header"><a href="{% url 'accounts:register' %}">Register</a></li>
                                <li class="dropdown-header"><a href="{% url 'accounts:login' %}">Login</a></li>
                                <li class="divider"></li>
                            </ul></li>
                        {% endif %}
                    </ul>
                </div></a>
            </div>
        </nav>


        <div class="help-button-div" style="position:fixed; left: 25px; top: 80px">
            <input type="button" id="help-button" class="help-button help-button-dormant" value="Help">
        </div>

        <div style="margin-top:140px; padding-top:20px;" class="container">

            <div styled="width:100%">
                {% load staticfiles %}
                {% block body_block %}{% endblock %}<br/>
            </div>

        </div>
<br/><br/><br/><br/><br/><br/>

    <script>

        // check help text exists so we need button
        $(function(){
            if ( $(".help-text").length < 1) {
                $("#help-button").hide();
            }
        });
        //the toggle JS for the help text-
        $(function(){
            $("#help-button").click(function(){
                $(".help-text").slideToggle();

                if ( $(this).hasClass("help-button-dormant")){
                    $('body').animate({scrollTop:0}, 'slow');
                }

                if ( $(this).hasClass("help-button-dormant") ) {
                    $(this).removeClass("help-button-dormant");
                    $(this).addClass("help-button-active");
                } else {
                    $(this).removeClass("help-button-active");
                    $(this).addClass("help-button-dormant");
                }


            });
        });
    </script>

</body>

<footer class="footer">
  <div  class="container">
      <div style="padding-top:16px;" class="col-md-10 col-md-offset-1">
          {% block buttons %}
              <a href="{% url 'bookmarks:silo' %}"><p class="footer_button">Home</p></a>
              <a href="{% url 'bookmarks:new-article' %}"><p class="footer_button">Add new articles</p></a>
              <a href="{% url 'bookmarks:manage-tags' %}"><p class="footer_button">Manage tags</p></a>
              <a href="{% url 'bookmarks:archives-list' %}"><p class="footer_button">Archives</p></a>
          {% endblock %}
      </div>
  </div>
</footer>
</html>